//constants/actionTypes.js

export const ADD_USER =                     'ADD_USER';
export const ADD_USERS =                    'ADD_USERS';
export const CURRENT_USER_LOGGED_IN =       'CURRENT_USER_LOGGED_IN';
export const CURRENT_USER_LOGGED_OUT =      'CURRENT_USER_LOGGED_OUT';
export const EMAIL_CHANGE =                 'EMAIL_CHANGE';
export const END_FETCHING =                 'END_FETCHING';
export const FETCHING =                     'FETCHING';
export const FETCH_GROUPS_FULFILLED =       'FETCH_GROUPS_FULFILLED';
export const FETCH_GROUPS_PENDING =         'FETCH_GROUPS_PENDING';
export const FETCH_GROUPS_REJECTED =        'FETCH_GROUPS_REJECTED';
export const FETCH_STORIES_FULFILLED =      'FETCH_STORIES_FULFILLED';
export const FETCH_STORIES_PENDING =        'FETCH_STORIES_PENDING';
export const FETCH_STORIES_REJECTED =       'FETCH_STORIES_REJECTED';
export const FETCH_USERS_FULFILLED =        'FETCH_USERS_FULFILLED';
export const FETCH_USERS_PENDING =          'FETCH_USERS_PENDING';
export const FETCH_USERS_REJECTED =         'FETCH_USERS_REJECTED';
// export const SHOW_USER =                    'SHOW_USER';
export const SHOWING_ITEM_CHANGE =          'SHOWING_ITEM_CHANGE';
// export const LOGIN_USER_REQUEST =           'LOGIN_USER_REQUEST';
// export const LOGIN_USER_FAILURE =           'LOGIN_USER_FAILURE';
// export const LOGIN_USER_SUCCESS =           'LOGIN_USER_SUCCESS';
// export const LOGOUT_USER =                  'LOGOUT_USER';
// export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const PURGE_GROUPS =                 'PURGE_GROUPS';
export const PURGE_STORIES =                'PURGE_STORIES';
export const PURGE_USERS =                  'PURGE_USERS';
// export const RECEIVE_PROTECTED_DATA =       'RECEIVE_PROTECTED_DATA';